name: Push Backend Imge to ghcr
run-name: Release Image GHCR
on: [push]
jobs:
  push-image-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checkout Anjay"
      - name: Checkout Code
        uses: actions/checout@v4
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }} # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
